### ISSUE TITLE
Launch a multiple camera

### ISSUE THREAD

**Issue by Franklein20** [tier4/ros2_v4l2_camera#12]
Hello Everyone 
I want to use this package to run the v4l2 driver into my project.
But i don't know , I don't know how to modify this repository in order to run several cameras at the same time.
Some ideas?

**Comment by knzo25** [comment]
@Franklein20 

Does this work for you?
https://github.com/tier4/edge_auto_jetson_launch/blob/main/edge_auto_jetson_launch/launch/v4l2_camera.launch.xml

**Comment by Franklein20** [comment]
i didn't test it. thanks
Is there a version with ROS2?

**Comment by knzo25** [comment]
I think the link I provided is for ROS2

**Comment by Franklein20** [comment]
Yes , correct. 
I'm trying to use it with the nvidia, but it still detect one camera.
I'm changing the config in adding one device.

**Comment by knzo25** [comment]
@Franklein20 
If there are no updates I will be closing this issue in a week
