### ISSUE TITLE
ubuntu 18.04 & ros2 dashing environment build unsuccessful

### ISSUE THREAD

**Issue by DavidTung0706** [tier4/ros2_v4l2_camera#15]
Please tell me if this package can work in this environment
ubuntu 18.04 & ros2 dashing

**Comment by drwnz** [comment]
Hi there, sorry we have only tested in Galactic and Humble.
For ROS1 we tested on Melodic, but we have not used ROS1 for some time now so newer features will not have been added to this branch.

**Comment by DavidTung0706** [comment]
I use the host as adlink - roscube_58G.  the roscube_58G environment only supports Ubuntu 18.04. and  ros2 version is dashing ,How to set it up?

**Comment by knzo25** [comment]
@DavidTung0706 
As mentioned, we support only galactic and humble for now. I will be closing this issue as it falls outside our scope
